### ISSUE TITLE
NoClassDefFoundError on Linux

### ISSUE THREAD

**Issue by spoeck** [miho/VWorkflows#43]
I got an exception when I call the connect()-methode of a VFlow:
`        sheetGraph.connect(outputObj, inputAct);`

My setup is:
Linux Mint 17.3
jdk1.8.0_60

It works on windows with same java version.
Thanks in advance!

StackTrace:
`Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: org/apache/commons/math3/geometry/euclidean/twod/Vector2D
	at eu.mihosoft.vrl.workflow.fx.FXFlowNodeSkin.nodeToSegments(FXFlowNodeSkin.java:752)
	at eu.mihosoft.vrl.workflow.fx.FXFlowNodeSkin.getConnectorEdges(FXFlowNodeSkin.java:808)
	at eu.mihosoft.vrl.workflow.fx.FXFlowNodeSkin.layoutConnector(FXFlowNodeSkin.java:369)
	at eu.mihosoft.vrl.workflow.fx.FXFlowNodeSkin.layoutConnectors(FXFlowNodeSkin.java:314)
	at eu.mihosoft.vrl.workflow.fx.FXConnectionSkin.add(FXConnectionSkin.java:619)
	at eu.mihosoft.vrl.workflow.VFlowImpl.createConnectionSkins(VFlowImpl.java:668)
	at eu.mihosoft.vrl.workflow.VFlowImpl.createConnectionSkins(VFlowImpl.java:646)
	at eu.mihosoft.vrl.workflow.VFlowImpl.access$500(VFlowImpl.java:71)
	at eu.mihosoft.vrl.workflow.VFlowImpl$2.onChanged(VFlowImpl.java:310)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at eu.mihosoft.vrl.workflow.ConnectionsImpl.add(ConnectionsImpl.java:88)
	at eu.mihosoft.vrl.workflow.ConnectionsImpl.add(ConnectionsImpl.java:105)
	at eu.mihosoft.vrl.workflow.FlowModelImpl.connect(FlowModelImpl.java:165)
	at eu.mihosoft.vrl.workflow.VFlowModelImpl.connect(VFlowModelImpl.java:150)
	at eu.mihosoft.vrl.workflow.VFlowImpl.connect(VFlowImpl.java:421)`

**Comment by miho** [comment]
Unfortunately, I can't reproduce it on my machine. Please share a sample application. Then I will try to reproduce the error. 

Thanks!

**Comment by spoeck** [comment]
I was able to solve the problem.

I added following dependency to my maven pom:
```
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-math3</artifactId>
	<version>3.3</version>
</dependency>
```


Thank you for your help!
