### ISSUE TITLE
Is this broken on JavaFX 9?

### ISSUE THREAD

**Issue by zilti** [miho/VWorkflows#61]
I tried getting the example described in http://mihosoft.eu/?p=523 to work. I replaced setSkinFactory with setSkinFactories, of course. The result on JavaFX 9 is... nothing.

Is this broken on JavaFX 9? If so, is there a workaround, or a fix, or a...?

**Comment by zilti** [comment]
Ah, yes, apparently.

```
Dez. 12, 2017 12:01:44 VORM. javafx.scene.control.Control doProcessCSS
SCHWERWIEGEND: The -fx-skin property has not been defined in CSS for FlowNodeWindow@7700972c[styleClass=window] and createDefaultSkin() returned null.
Dez. 12, 2017 12:01:44 VORM. javafx.scene.control.Control loadSkinClass
SCHWERWIEGEND: Failed to load skin 'jfxtras.internal.scene.control.skin.window.DefaultWindowSkin' for control FlowNodeWindow@25cdeea9[styleClass=window]
java.lang.NoSuchMethodError: com.sun.javafx.tk.FontLoader.computeStringWidth(Ljava/lang/String;Ljavafx/scene/text/Font;)F
        at jfxtras.internal.scene.control.skin.window.TitleBar.setTitle(DefaultWindowSkin.java:960)
        at jfxtras.internal.scene.control.skin.window.DefaultWindowSkin.<init>(DefaultWindowSkin.java:99)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at javafx.controls/javafx.scene.control.Control.loadSkinClass(Control.java:754)
        at javafx.controls/javafx.scene.control.Control$5.invalidated(Control.java:680)
        at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
        at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
        at javafx.graphics/javafx.css.StyleableStringProperty.set(StyleableStringProperty.java:83)
        at javafx.controls/javafx.scene.control.Control$5.set(Control.java:672)
        at javafx.graphics/javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:69)
        at javafx.graphics/javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:45)
        at javafx.graphics/javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:772)
        at javafx.graphics/javafx.scene.Node.doProcessCSS(Node.java:9631)
        at javafx.graphics/javafx.scene.Node.access$900(Node.java:398)
        at javafx.graphics/javafx.scene.Node$1.doProcessCSS(Node.java:471)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:206)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(ParentHelper.java:95)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSS(ParentHelper.java:65)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1388)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1419)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9513)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
        at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1770)
        at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:394)
        at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1098)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1186)
        at javafx.graphics/javafx.stage.Window.show(Window.java:1201)
        at javafx.graphics/javafx.stage.Stage.show(Stage.java:276)
        at videocapture.settings$init.invokeStatic(settings.clj:110)
        at videocapture.settings$init.invoke(settings.clj:102)
        at videocapture.core$start$fn__10894$fn__10895.invoke(core.clj:450)
        at videocapture.core.proxy$java.lang.Object$EventHandler$c65909a4.handle(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4083)
        at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1600(Scene.java:4029)
        at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2146)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2620)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
        at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by miho** [comment]
This should be fixed.
